services:
  backend:
    build:
      context: ./backend
    container_name: django-app
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8000:8000"
    working_dir: /app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: vue-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:5173:5173"
    working_dir: /app
    command: npm run dev

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: faqup_db
      POSTGRES_USER: faqup_user
      POSTGRES_PASSWORD: faqup_pass
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "faqup_user", "-d", "faqup_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
